server:
  port: 8081

keycloak:
  auth-server-url: http://localhost:8080/
  realm: SpringBootKeycloak
  resource: login-app
  public-client: true
  principal-attribute: preferred_username
  ssl-required: external