server:
  port: 8081

keycloak:
  auth-server-url: http://localhost:8080/
  realm: SpringBootKeycloak
  resource: login-app
  public-client: true
  principal-attribute: preferred_username
  ssl-required: external
  use-resource-role-mappings: true
  
  security-constraints[0]:
    authRoles[0]: user
    securityCollections[0]:
      patterns[0]: /user/*
  security-constraints[1]:
    authRoles[0]: admin
    securityCollections[0]:
      patterns[0]: /admin/*